name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          deploy-branch: master
          deploy-repo: sdx-workshop/sdx-workshop.github.io.git
          access-token: ${{ secrets.ACCESS_TOKEN }}